### ISSUE TITLE
Is there any reason or usecase to make `Thread::setInterval` and `Thread::shouldRun` virtual?

### ISSUE THREAD

**Issue by CAHEK7** [ivanseidel/ArduinoThread#14]
It seems `Thread::setInterval` and `Thread::shouldRun` are very basic and key methods of `Thread` class. They implement time intervals feature and I can't realize any real usecase where we have to override intervals handling as well as "enabled\disabled" handling.
At the same time `Thread::shouldRun` is very hot function and it would be nice to reduce its overhead as much as possible.
So is there any reason to make those functions virtual?

**Comment by ivanseidel** [comment]
Hi,

The reason is to allow extension of it. Take the example `CustomTimedThread` for instance:

https://github.com/ivanseidel/ArduinoThread/blob/master/examples/CustomTimedThread/CustomTimedThread.ino

**Comment by CAHEK7** [comment]
It makes sense, thanks!
Checked almost all the examples, even ArduinoSensor repository, but forgot to check that one.

**Comment by ivanseidel** [comment]
It happens haha. Closing this issue, but if you have any idea, we can re-open it.
