### ISSUE TITLE
Warning when compiling ThreadController.cpp

### ISSUE THREAD

**Issue by LBertrandDC** [ivanseidel/ArduinoThread#15]
Hello,
This warning doesn't seem to have any effect but...
`../ThreadController.cpp: In member function 'void ThreadController::remove(int)':
../ThreadController.cpp:68:7: warning: unused variable 'found' [-Wunused-variable]
  bool found = false;
`
The unused variable should be cleaned up by removing the declaration
`void ThreadController::remove(int id){`
`    // Find Threads with the id, and removes`
`    bool found = false;  // <--- this line`
Thanks

**Comment by ivanseidel** [comment]
Can you clean it up and make a pull request? Closing for now.
