### ISSUE TITLE
Getting error with Threads in NODEMCU Devkit 1.0

### ISSUE THREAD

**Issue by pipoblak** [ivanseidel/ArduinoThread#16]
Hi, i'm using that code to control with Serial and Fastleds the Leds of a Room :
https://gist.github.com/pipoblak/a83f9f7475dfe4150f183a3deb801650

And after a time, i recive that error:

ets Jan 8 2013,rst cause:4, boot mode:(3,7)

wdt reset
load 0x4010f000, len 1384, room 16
tail 8
chksum 0x2d
csum 0x2d
v09f0c112

**Comment by joaopedrovbs** [comment]
Hey take a look at this! 

https://github.com/esp8266/Arduino/issues/1328

Maybe the problem is hardware related as they were discussing!
Also, watch out for the delay() function in your code!
