### ISSUE TITLE
Bug ThreadController::run()

### ISSUE THREAD

**Issue by wvmcastro** [ivanseidel/ArduinoThread#19]
A segunda condição do laço (checks <= cached_size) sempre será verdade, pois checks só é incrementada quando thread[i] != NULL. Logo o laço termina a execução apenas por causa da primeira condição (i < MAX_THREADS). Talvez a segunda condição seria (checks < cached_size), assim o laço pode terminar a execução assim que todas as threads armazenadas forem executadas.

**Comment by ivanseidel** [comment]
Bem notado,
Você pode fazer um pull request com as alterações por favor?

**Comment by wvmcastro** [comment]
Sim, irei fazer isso.

**Comment by ivanseidel** [comment]
Mergeado, valeu!
