### ISSUE TITLE
second thread is not running

### ISSUE THREAD

**Issue by himanshu-hearthacker** [ivanseidel/ArduinoThread#24]
I am running code with two simple thread. on one thread i have include some GSM commands and on other thread there is just print statement.
At a time i am able to run only 1 thread at a time.
here is my code plz help me out---`#include <SoftwareSerial.h>
#include <Thread.h>
#define debug 1
#define Line_RX 3 //UART RX
#define Line_TX 2 //UART TX
SoftwareSerial mySerial (Line_TX, Line_RX); //initialize software serial

int ledPin = 6;

//My simple Thread
Thread myThread1 = Thread();
Thread myThread2 = Thread();

  void niceCallback1(){

 // My AT commads goes here
// I am runnig 7 at command for TCP connection establishment

}

void niceCallback2(){
    // right now i have included only print statement here
}

void setup() {
  delay(3000);
  // put your setup code here, to run once:
  mySerial.begin(19200);
  delay(1000);
  Serial.begin(19200);
  delay(1000);
  myThread1.onRun(niceCallback1);
  myThread1.setInterval(6000);
  myThread2.onRun(niceCallback2);
  myThread2.setInterval(12000);

  // checks if thread should run
  if(myThread1.shouldRun())
   { mySerial.println("thread 1 starting");
   myThread1.run();}
   // checks if thread should run
  if(myThread2.shouldRun())
    {
      mySerial.println("thread 2 starting");
      myThread2.run();}

}

void loop() {
  
}`

**Comment by CAHEK7** [comment]
You have to call "thread.run()" in the loop(), not in setup().

But if you want to execute more than one thread, you should use ThreadController or StaticThreadController classes. Readme contains all the information about it. Also there are a couple of fancy examples for ThreadController (https://github.com/ivanseidel/ArduinoThread/blob/master/examples/SimpleThreadController/SimpleThreadController.ino)  and StaticThreadController (https://github.com/ivanseidel/ArduinoThread/blob/master/examples/StaticThreadController/StaticThreadController.ino).
And don't forget to put "controller.run()" into the loop().
