### ISSUE TITLE
The threads stop working after 49 days.

### ISSUE THREAD

**Issue by daviinacio** [ivanseidel/ArduinoThread#41]
I have a clock project ([White_Led_Digital_Clock](https://github.com/daviinacio/White_Led_Digital_Clock)).
After 49 days the threads stopped working.
Probably because, the unsigned long from millis() arrives to the max value (4294967295).

4294967295 / (1000 * 60 * 60 * 24) = 49,71026961805556 days

**Comment by mamuncloud** [comment]
maybe you can add qualifier variable, "volatile" ...

**Comment by daviinacio** [comment]
I made some tests in millis() overflow, and that is working..

```serial
COOL! I'm running on: 4294965295
COOL! I'm running on: 4294965795
COOL! I'm running on: 4294966295
COOL! I'm running on: 4294966795
COOL! I'm running on: 4294967295
COOL! I'm running on: 499
COOL! I'm running on: 999
COOL! I'm running on: 1499
COOL! I'm running on: 1999
COOL! I'm running on: 2499
```
