### ISSUE TITLE
Passing Parameters to callback functions

### ISSUE THREAD

**Issue by WhiteSpin** [ivanseidel/ArduinoThread#7]
Great little Project and documentation! However I have a question:

Is there a way to pass function parameters to a function in a thread? 
I am imagining something like `mythread.run(<params>)`

**Comment by ivanseidel** [comment]
Thanks @WhiteSpin!

Well, you can do whatever you want with the Threads, by extending them. The idea was to give you the simplest way to do timed actions, and let you extend it the way you want. Here is a fork that have done something similar: 
https://github.com/tlextrait/ArduinoThread/commit/88e761ea563bedef2e982d1e8ecd83b7a49e1277

(closing, but if still any doubt, fell free to ask)
